/* empty css                      */import{S as m,i as n}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const f="https://pixabay.com/api/",d=r=>{const o=new URLSearchParams({key:"47362908-c1a65ba58d6ddf3afd8961379",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`${f}?${o}`).then(s=>{if(!s.ok)throw new Error(s.statusText);return s.json()})};let l;const p=({webformatURL:r,largeImageURL:o,tags:s,likes:a,views:e,comments:t,downloads:i})=>`<a href="${o}" class="gallery_item">
    <img src="${r}" alt="${s}" class="gallery__image" />
    <div class="info">
    <p class="info-item"><b>Likes</b> ${a}</p>
    <p class="info-item"><b>Views</b> ${e}</p>
    <p class="info-item"><b>Comments</b> ${t}</p>
    <p class="info-item"><b>Downloads</b> ${i}</p>
    </div>
    </a>`;function h(r){const o=document.querySelector(".js-gallery");o.innerHTML=r.map(p).join(""),y()}function y(){l?l.refresh():l=new m(".js-gallery a",{captions:!0,captionsData:"alt",captionDelay:250})}const g=document.querySelector(".js-search-form");document.querySelector(".js-search-input");const b=document.querySelector(".js-gallery"),c=document.querySelector(".loader");g.addEventListener("submit",L);function u(r){r?c.classList.remove("hidden"):c.classList.add("hidden")}function L(r){r.preventDefault();const o=r.target.elements.user_query.value.trim();if(!o){n.error({message:"Please write smth normal.",position:"topRight"});return}b.innerHTML="",u(!0),d(o).then(s=>{if(s.total===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(s.hits)}).catch(s=>{console.log(s.message),n.error({message:"Failed to fetch images. Please try again later.",position:"topRight"})}).finally(()=>{u(!1)}),r.target.elements.user_query.value=""}
//# sourceMappingURL=index.js.map
